/**
 * This Class Created By Lord_Crystalyx.
 */
// Date: 24.06.2015 20:55:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package RW.Client.Model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * @author Lord_Crystalyx Created using Tabula 4.1.1
 */
public class Head extends ModelBiped
{
	// fields
	ModelRenderer Shape32;
	ModelRenderer Shape29;
	ModelRenderer Shape31;
	ModelRenderer Shape30;
	ModelRenderer Shape28;
	ModelRenderer Shape0;
	ModelRenderer Shape27;
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;
	ModelRenderer Shape24;
	ModelRenderer Shape25;
	ModelRenderer Shape26;

	public Head()
	{
		textureWidth = 128;
		textureHeight = 64;

		Shape32 = new ModelRenderer(this, 5, 7);
		Shape32.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape32.setRotationPoint(-4F, -8.3F, -4F);
		Shape32.setTextureSize(128, 64);
		setRotation(Shape32, 0.5585054F, -0.2268928F, 0F);
		Shape29 = new ModelRenderer(this, 4, 33);
		Shape29.addBox(0F, 0F, 0F, 6, 1, 4);
		Shape29.setRotationPoint(-3F, -7F, -7F);
		Shape29.setTextureSize(128, 64);
		setRotation(Shape29, 0.5934119F, 0F, 0F);
		Shape31 = new ModelRenderer(this, 46, 17);
		Shape31.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape31.setRotationPoint(-4F, -8F, -5F);
		Shape31.setTextureSize(128, 64);
		setRotation(Shape31, 0.296706F, -0.2268928F, 0F);
		Shape30 = new ModelRenderer(this, 13, 23);
		Shape30.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape30.setRotationPoint(2F, -3F, -5.5F);
		Shape30.setTextureSize(128, 64);
		setRotation(Shape30, 0F, 0.7504916F, 0F);
		Shape28 = new ModelRenderer(this, 6, 44);
		Shape28.addBox(0F, 0F, 0F, 6, 1, 3);
		Shape28.setRotationPoint(-3F, 0F, -6F);
		Shape28.setTextureSize(128, 64);
		setRotation(Shape28, 0F, 0F, 0F);
		Shape0 = new ModelRenderer(this, 105, 0);
		Shape0.addBox(0F, 0F, 0F, 8, 3, 1);
		Shape0.setRotationPoint(-4F, -8F, -5F);
		Shape0.setTextureSize(128, 64);
		setRotation(Shape0, 0F, 0F, 0F);
		Shape27 = new ModelRenderer(this, 9, 53);
		Shape27.addBox(0F, 0F, 0F, 4, 3, 1);
		Shape27.setRotationPoint(-2F, -2F, -7.1F);
		Shape27.setTextureSize(128, 64);
		setRotation(Shape27, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 91, 5);
		Shape1.addBox(0F, 0F, 0F, 8, 1, 8);
		Shape1.setRotationPoint(-4F, -9F, -4F);
		Shape1.setTextureSize(128, 64);
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 105, 16);
		Shape2.addBox(0F, 0F, 0F, 1, 4, 8);
		Shape2.setRotationPoint(-5F, -8F, -4F);
		Shape2.setTextureSize(128, 64);
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 96, 17);
		Shape3.addBox(0F, 0F, 0F, 1, 7, 2);
		Shape3.setRotationPoint(-5F, -5F, -4F);
		Shape3.setTextureSize(128, 64);
		setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 87, 17);
		Shape4.addBox(0F, 0F, 0F, 1, 7, 2);
		Shape4.setRotationPoint(4F, -5F, -4F);
		Shape4.setTextureSize(128, 64);
		setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 70, 0);
		Shape5.addBox(0F, 0F, 0F, 1, 4, 8);
		Shape5.setRotationPoint(4F, -8F, -4F);
		Shape5.setTextureSize(128, 64);
		setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 97, 30);
		Shape6.addBox(0F, 0F, 0F, 8, 1, 5);
		Shape6.setRotationPoint(-4F, -8F, 4F);
		Shape6.setTextureSize(128, 64);
		setRotation(Shape6, -1.151917F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 97, 38);
		Shape7.addBox(0F, 0F, 0F, 7, 1, 6);
		Shape7.setRotationPoint(-3.5F, -6F, 4F);
		Shape7.setTextureSize(128, 64);
		setRotation(Shape7, -1.151917F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 97, 47);
		Shape8.addBox(0F, 0F, 0F, 6, 1, 7);
		Shape8.setRotationPoint(-3F, -4F, 4F);
		Shape8.setTextureSize(128, 64);
		setRotation(Shape8, -1.186824F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 69, 47);
		Shape9.addBox(0F, 0F, 0F, 5, 1, 8);
		Shape9.setRotationPoint(-2.5F, -2F, 4F);
		Shape9.setTextureSize(128, 64);
		setRotation(Shape9, -1.256637F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 39, 47);
		Shape10.addBox(0F, 0F, 0F, 4, 1, 10);
		Shape10.setRotationPoint(-2F, -1F, 4F);
		Shape10.setTextureSize(128, 64);
		setRotation(Shape10, -1.343904F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 64, 31);
		Shape11.addBox(0F, 0F, 0F, 3, 1, 12);
		Shape11.setRotationPoint(-1.5F, 1F, 5F);
		Shape11.setTextureSize(128, 64);
		setRotation(Shape11, -1.58825F, 0F, 0F);
		Shape12 = new ModelRenderer(this, 105, 57);
		Shape12.addBox(0F, 0F, 0F, 8, 3, 1);
		Shape12.setRotationPoint(-4F, -2F, -5F);
		Shape12.setTextureSize(128, 64);
		setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new ModelRenderer(this, 94, 0);
		Shape13.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape13.setRotationPoint(-4F, -7F, -5F);
		Shape13.setTextureSize(128, 64);
		Shape13.mirror = false;
		setRotation(Shape13, 0F, 0.7853982F, 0F);
		Shape14 = new ModelRenderer(this, 94, 58);
		Shape14.addBox(-3F, 0F, 0F, 3, 2, 1);
		Shape14.setRotationPoint(4F, -7F, -5F);
		Shape14.setTextureSize(128, 64);
		Shape14.mirror = false;
		setRotation(Shape14, 0F, -0.7853982F, 0F);
		Shape15 = new ModelRenderer(this, 81, 58);
		Shape15.addBox(0F, 0F, 0F, 4, 2, 1);
		Shape15.setRotationPoint(-2F, -7F, -7.1F);
		Shape15.setTextureSize(128, 64);
		Shape15.mirror = false;
		setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new ModelRenderer(this, 70, 58);
		Shape16.addBox(0F, 0F, 0F, 3, 3, 1);
		Shape16.setRotationPoint(-4F, -2F, -5F);
		Shape16.setTextureSize(128, 64);
		Shape16.mirror = false;
		setRotation(Shape16, 0F, 0.7853982F, 0F);
		Shape17 = new ModelRenderer(this, 59, 60);
		Shape17.addBox(0F, 0F, 0F, 3, 3, 1);
		Shape17.setRotationPoint(2F, -2F, -7F);
		Shape17.setTextureSize(128, 64);
		Shape17.mirror = false;
		setRotation(Shape17, 0F, -0.7853982F, 0F);
		Shape18 = new ModelRenderer(this, 63, 0);
		Shape18.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape18.setRotationPoint(-2F, -5F, -6.5F);
		Shape18.setTextureSize(128, 64);
		Shape18.mirror = false;
		setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new ModelRenderer(this, 56, 0);
		Shape19.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape19.setRotationPoint(1F, -5F, -6.5F);
		Shape19.setTextureSize(128, 64);
		Shape19.mirror = false;
		setRotation(Shape19, 0F, 0F, 0F);
		Shape20 = new ModelRenderer(this, 49, 0);
		Shape20.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape20.setRotationPoint(-2.8F, -3F, -6F);
		Shape20.setTextureSize(128, 64);
		Shape20.mirror = false;
		setRotation(Shape20, 0F, -0.7504916F, 0F);
		Shape21 = new ModelRenderer(this, 66, 18);
		Shape21.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape21.setRotationPoint(3F, -8F, -5F);
		Shape21.setTextureSize(128, 64);
		Shape21.mirror = false;
		setRotation(Shape21, 0.3141593F, 0.2268928F, 0F);
		Shape22 = new ModelRenderer(this, 45, 35);
		Shape22.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape22.setRotationPoint(3F, -8.3F, -4F);
		Shape22.setTextureSize(128, 64);
		Shape22.mirror = false;
		setRotation(Shape22, 0.5585054F, 0.2268928F, 0F);
		Shape23 = new ModelRenderer(this, 42, 0);
		Shape23.addBox(0F, 0F, 0F, 1, 11, 1);
		Shape23.setRotationPoint(3F, -5F, 3F);
		Shape23.setTextureSize(128, 64);
		Shape23.mirror = false;
		setRotation(Shape23, 0.0872665F, 0F, -0.2094395F);
		Shape24 = new ModelRenderer(this, 34, 0);
		Shape24.addBox(0F, 0F, 0F, 1, 11, 1);
		Shape24.setRotationPoint(-4F, -5F, 3F);
		Shape24.setTextureSize(128, 64);
		Shape24.mirror = false;
		setRotation(Shape24, 0.0872665F, 0F, 0.2094395F);
		Shape25 = new ModelRenderer(this, 26, 0);
		Shape25.addBox(0F, 0F, 0F, 1, 9, 1);
		Shape25.setRotationPoint(-5.3F, 1F, 3.5F);
		Shape25.setTextureSize(128, 64);
		Shape25.mirror = false;
		setRotation(Shape25, 0.0872665F, 0F, 0.6632251F);
		Shape26 = new ModelRenderer(this, 38, 15);
		Shape26.addBox(0F, 0F, 0F, 1, 9, 1);
		Shape26.setRotationPoint(4.3F, 1F, 3.5F);
		Shape26.setTextureSize(128, 64);
		Shape26.mirror = false;
		setRotation(Shape26, 0.0872665F, 0F, -0.6632251F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, ent);
		Shape32.render(f5);
		Shape29.render(f5);
		Shape31.render(f5);
		Shape30.render(f5);
		Shape28.render(f5);
		Shape0.render(f5);
		Shape27.render(f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
		Shape16.render(f5);
		Shape17.render(f5);
		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
		Shape24.render(f5);
		Shape25.render(f5);
		Shape26.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}

}
